name: Create CNAME

on:
  push:
    branches: ["gh-pages"]
  pull_request:
    branches: ["gh-pages"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create File
        # You may pin to the exact commit or the version.
        # uses: finnp/create-file-action@af8500fe0b0c5d8e04934f8bb62b9dda872c5803
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "CNAME"
          FILE_DATA: "hydrametry.com"
